apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.registry }}/{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          ports:
            - containerPort: {{ .Values.backend.servicePort }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.servicePort }}
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.servicePort }}
            initialDelaySeconds: 30

