apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: {{ .Values.namespace }}
spec:
  serviceName: database
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.database.image }}:{{ .Values.database.tag }}"
          ports:
            - containerPort: {{ .Values.database.port }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.database.storage }}
